import type { DeleteAction, FieldType, RelationCardinality, SchemaDocument, SchemaEnum, SchemaField, SchemaIndex, SchemaNote, SchemaTable, ValidationIssue, XYPosition } from './types';
export declare const FIELD_TYPES: FieldType[];
export declare const CARDINALITIES: RelationCardinality[];
export declare const DELETE_ACTIONS: DeleteAction[];
export declare const TYPE_COLORS: Record<FieldType, string>;
export declare function createId(prefix: string): string;
export declare function touchSchema(schema: SchemaDocument): SchemaDocument;
export declare function sourceHandleId(fieldId: string): string;
export declare function targetHandleId(fieldId: string): string;
export declare function parseFieldHandle(handleId?: string | null): string | null;
export declare function createField(overrides?: Partial<SchemaField>): SchemaField;
export declare function createTable(name: string, position: XYPosition): SchemaTable;
export declare function createIndex(fields: string[]): SchemaIndex;
export declare function createEnum(position: XYPosition): SchemaEnum;
export declare function createNote(position: XYPosition): SchemaNote;
export declare function createStarterSchema(): SchemaDocument;
export declare function createBlankSchema(): SchemaDocument;
export declare function createTemplateSchema(template: 'auth' | 'commerce' | 'content'): SchemaDocument;
export declare function normalizeSchema(value: unknown): SchemaDocument;
export declare function validateSchema(schema: SchemaDocument): ValidationIssue[];
